wa/awww/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
                  path("accounts/", include("django.contrib.auth.urls")),
                  path('', include('compiler.urls')),
                  path('admin/', admin.site.urls),
              ] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wa/compiler/urls.py
from django.urls import path

from . import views

app_name = 'compiler'
urlpatterns = [
    path('', views.index, name='index'),
    path('files/tree', views.directories_tree, name='directories_tree'),
    path('files/<int:file_info_id>/show', views.show_file, name='show_file'),
    path('files/<int:file_info_id>/compile', views.compile_file, name='compile_file'),
    path('files/<int:file_info_id>/sections', views.change_sections, name='change_sections'),
    path('files/<int:file_info_id>/delete', views.delete_file, name='delete_file'),
    path('files/upload', views.upload_file, name='upload_file'),
    path('files/directory/create', views.create_directory, name='create_directory'),
]

wa/compiler/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class FileInfo(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100, null=True, blank=True)
    creation_date = models.DateTimeField(default=timezone.now, editable=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)
    available_modification_date = models.DateTimeField(auto_now=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Directory(models.Model):
    id = models.AutoField(primary_key=True)
    info = models.OneToOneField(FileInfo, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def is_file(self):
        return False

    def __str__(self):
        return self.info.name

    def get_children(self):
        return list(Directory.objects.filter(parent=self, info__available=True)) \
            + list(File.objects.filter(parent=self, info__available=True))

    def has_children(self):
        return len(self.get_children()) > 0


class File(models.Model):
    id = models.AutoField(primary_key=True)
    info = models.OneToOneField(FileInfo, on_delete=models.CASCADE)
    parent = models.ForeignKey(Directory, on_delete=models.CASCADE)
    content = models.FileField(upload_to='files/')

    def is_file(self):
        return True

    def __str__(self):
        return self.info.name


class Section(models.Model):
    id = models.AutoField(primary_key=True)
    file = models.ForeignKey(File, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, null=True, blank=True)
    description = models.CharField(max_length=100, null=True, blank=True)
    creation_date = models.DateTimeField(default=timezone.now, editable=False)
    start_row = models.PositiveIntegerField()
    end_row = models.PositiveIntegerField()
    # to represent subsections
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    class SectionType(models.TextChoices):
        PROCEDURE = 'PROCEDURE', 'Procedure'
        COMMENT = 'COMMENT', 'Comment'
        DIRECTIVE = 'DIRECTIVE', 'Directive'
        VARIABLE = 'VARIABLE', 'Variable'
        INLINE_ASM = 'INLINE_ASM', 'Inline Assembly'
        FUNCTION = 'FUNCTION', 'Function'
        UNKNOWN = 'UNKNOWN', 'Unknown'

    type = models.CharField(max_length=20, choices=SectionType.choices, default=SectionType.UNKNOWN)

    class SectionStatus(models.TextChoices):
        COMPILES_WITH_WARNINGS = 'COMPILES_WITH_WARNINGS', 'Compiles with warnings'
        COMPILE_OK = 'COMPILE_OK', 'Compiles'
        COMPILE_ERROR = 'COMPILE_ERROR', 'Compile error'

    status = models.CharField(max_length=30, choices=SectionStatus.choices, default=SectionStatus.COMPILE_OK)

    additional_status_info = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.file.info.name

wa/compiler/forms.py
from django import forms
from django.core.exceptions import ValidationError

from compiler.models import Section


class CreateDirectoryForm(forms.Form):
    name = forms.CharField(max_length=20)
    description = forms.CharField(max_length=100, required=False)
    parent = forms.IntegerField(min_value=-1, required=False)  # (-1, '', None) mean root directory

    description.widget.attrs.update({"class": "form-control", "placeholder": "Description (optional)"})
    name.widget.attrs.update({"class": "form-control", "placeholder": "Directory name"})
    parent.widget = parent.hidden_widget()


class UploadFileForm(forms.Form):
    description = forms.CharField(max_length=100, required=False)
    parent = forms.IntegerField(min_value=0, required=True)  # we want to know where to put the file
    file = forms.FileField()

    # add extra validation for file extension
    def clean_file(self):
        uploaded_file = self.cleaned_data.get('file')
        if uploaded_file:
            file_extension = uploaded_file.name.split('.')[-1].lower()
            if file_extension not in ['h', 'c', 'cc']:
                raise ValidationError('Invalid file type. Only .h, .c and .cc are allowed.')
        return uploaded_file

    description.widget.attrs.update({"class": "form-control", "placeholder": "Description (optional)"})
    file.widget.attrs.update({"class": "form-control"})
    parent.widget = parent.hidden_widget()


class ChangeSectionsForm(forms.Form):
    sectionType = forms.ChoiceField(choices=Section.SectionType.choices)
    start = forms.IntegerField()
    end = forms.IntegerField()

    # check if start < end
    def clean(self):
        cleaned_data = super().clean()
        start = cleaned_data.get("start")
        end = cleaned_data.get("end")
        if start and end:
            if start > end:
                raise ValidationError("Start row must be lower than end row.")

    start.widget = start.hidden_widget()
    end.widget = end.hidden_widget()
    sectionType.widget.attrs.update({"class": "form-control h-100"})


class CompileForm(forms.Form):
    # this form will always be valid because of the default values
    BLANK_CHOICE = ("Default", "Select an option...")
    BLANK_CHOICE_MCS51 = ("Default", "Select an option for MCS51...")
    BLANK_CHOICE_Z80 = ("Default", "Select an option for Z80...")
    BLANK_CHOICE_STM8 = ("Default", "Select an option for STM8...")

    standard = forms.ChoiceField(
        choices=[
            BLANK_CHOICE,
            ("--std-c89", "C89"),
            ("--std-c99", "C99"),
            ("--std-c11", "C11")
        ], required=False)

    optimization = forms.MultipleChoiceField(
        choices=[
            ("--nolabelopt", "Will not optimize labels (makes the dumpfiles more readable)."),
            ("--noloopreverse", "Will not do loop reversal optimization."),
            ("--no-peep", "Disable peep-hole optimization with built-in rules."),
            ("--opt-code-speed", "The compiler will optimize code generation towards fast code.")
        ], required=False)

    processor = forms.ChoiceField(
        choices=[
            BLANK_CHOICE,
            ("-mmcs51", "MCS51"),
            ("-mz80", "Z80"),
            ("-mstm8", "STM8")
        ], required=False)

    options_MCS51 = forms.ChoiceField(
        choices=[
            BLANK_CHOICE_MCS51,
            ("--model-small", "Generate code for Small model programs. This is the default model."),
            ("--model-medium", "Generate code for Medium model programs."),
            ("--model-large", "Generate code for Large model programs."),
        ], required=False)

    options_Z80 = forms.ChoiceField(
        choices=[
            BLANK_CHOICE_Z80,
            ("--fno-omit-frame-pointer", "Never omit the frame pointer."),
            ("--callee-saves-bc", "Force a called function to always save BC."),
            ("--reserve-regs-iy", "This option tells the compiler that it is not allowed to use register "
                                  "pair iy. This option is incompatible with --fomit-frame-pointer.")
        ], required=False)

    options_STM8 = forms.ChoiceField(
        choices=[
            BLANK_CHOICE_STM8,
            ("--model-medium", "Generate code for Medium model programs. This is the default model."),
            ("--model-large", "Generate code for Large model programs.")
        ], required=False)

    standard.widget.attrs.update({"class": "form-control"})
    optimization.widget.attrs.update({"class": "form-control"})
    processor.widget.attrs.update({"class": "form-control"})
    options_MCS51.widget.attrs.update({"class": "form-control"})
    options_Z80.widget.attrs.update({"class": "form-control"})
    options_STM8.widget.attrs.update({"class": "form-control"})

wa/compiler/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt

from compiler import utils
from compiler.forms import CompileForm, ChangeSectionsForm, UploadFileForm, CreateDirectoryForm
from compiler.models import FileInfo, File, Section, Directory


def index(request):
    context = dict()
    context['directories'] = utils.get_root_directories(request.user)
    context['form'] = CompileForm()
    context['sectionsForm'] = ChangeSectionsForm()
    context['fileForm'] = UploadFileForm()
    context['directoryForm'] = CreateDirectoryForm()
    return render(request, 'compiler/index.html', context)


@login_required
def compile_file(request, file_info_id):
    if request.method == 'POST' and utils.test_ownership(request.user, file_info_id):
        context = dict()
        # Get file
        file_info = get_object_or_404(FileInfo, pk=file_info_id)
        file = get_object_or_404(File, info=file_info)
        # Get compilation options
        form = CompileForm(request.POST)
        if form.is_valid():
            options = utils.get_options(form)
            # Compiling the file, saving the output to the temporary directory
            import os
            temporary_path = file.content.path.replace("media/files", "temporary")
            os.chdir(os.path.dirname(temporary_path))
            # Compile with options
            cmd = 'sdcc' + ' -S ' + options + ' ' + file.content.path
            context['cmd'] = cmd
            err_message = os.popen(cmd + ' 2>&1').read()
            status_code = 200
            # Get output
            try:
                with open(temporary_path.replace('.c', '.asm'), 'r') as output_file:
                    [headers, bodies] = utils.separate_assembly_sections(output_file.read())
                    context['headers'] = headers
                    context['bodies'] = bodies
            except FileNotFoundError:
                context['errors'] = utils.parse_err_message(err_message)
                status_code = 400
            # Remove all files from temporary directory
            os.system('rm -rf ' + os.path.dirname(temporary_path) + '/*')
            return JsonResponse(status=status_code, data=context)
    return utils.JSON_BAD_REQUEST


@login_required
def show_file(request, file_info_id):
    if not utils.test_ownership(request.user, file_info_id):
        return utils.JSON_BAD_REQUEST
    file_info = get_object_or_404(FileInfo, pk=file_info_id)
    file = get_object_or_404(File, info=file_info)
    content = file.content.read().decode('utf-8')
    code = utils.get_formatted_code(Section.objects.filter(file=file), content.split('\n'))
    return JsonResponse({'code': code})


@login_required
def change_sections(request, file_info_id):
    if request.method == 'POST' and utils.test_ownership(request.user, file_info_id):
        form = ChangeSectionsForm(request.POST)
        if form.is_valid():
            file_info = get_object_or_404(FileInfo, pk=file_info_id)
            file = get_object_or_404(File, info=file_info)
            # Get sections
            utils.replace_sections(form.cleaned_data['start'],
                                   form.cleaned_data['end'],
                                   form.cleaned_data['sectionType'],
                                   file)
            return utils.JSON_OK
        else:
            print(form.errors)
    return utils.JSON_BAD_REQUEST


@login_required
def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            # Parse form
            name = form.cleaned_data['file'].name
            description = form.cleaned_data['description']
            file_info_id = form.cleaned_data['parent']
            # Get parent directory
            parent_info_id = get_object_or_404(FileInfo, pk=file_info_id)
            parent = get_object_or_404(Directory, info=parent_info_id)
            # Create file info and file
            file_info = FileInfo.objects.create(name=name, description=description, owner=request.user)
            file = File.objects.create(info=file_info, parent=parent, content=form.cleaned_data['file'])
            utils.create_file_sections(file.content.read().decode('utf-8'), file)
            file.save()
            return utils.JSON_OK
        else:
            print(form.errors)
    return utils.JSON_BAD_REQUEST


@login_required
def create_directory(request):
    if request.method == 'POST':
        form = CreateDirectoryForm(request.POST)
        if form.is_valid():
            # Parse form
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            parent_info_id = form.cleaned_data['parent']
            # Get parent directory
            parent = utils.get_parent(parent_info_id)
            # Create directory info and directory
            directory_info = FileInfo.objects.create(name=name, description=description, owner=request.user)
            directory = Directory.objects.create(info=directory_info, parent=parent)
            directory.save()
            return utils.JSON_OK
        else:
            print(form.errors)
    return utils.JSON_BAD_REQUEST


@login_required
@csrf_exempt
def delete_file(request, file_info_id):
    if request.method == 'DELETE' and utils.test_ownership(request.user, file_info_id):
        # Get file
        file_info = get_object_or_404(FileInfo, pk=file_info_id)
        file_info.available = False
        file_info.save()
        return utils.JSON_OK
    return utils.JSON_BAD_REQUEST


def directories_tree(request):
    return render(request, 'compiler/directories.html', {'directories': utils.get_root_directories(request.user)})

wa/compiler/templates/compiler/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <title>AWW</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'compiler/styles.css' %}?{% now "U" %}">
</head>

<body>
<div class="grid-container">
    <div class="grid-item navbar navbar-expand-sm navbar-dark">
        <div class="container-fluid">
            <div class="d-flex align-items-center">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="theme-switch-wrapper">
                    <label class="switch">
                        <input type="checkbox" id="themeButton">
                        <span class="slider round"></span>
                    </label>
                </div>
            </div>
            <div class="collapse navbar-collapse p-2" id="navbarToggleExternalContent">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href={% url 'compiler:index' %}>Home</a>
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'logout' %}" onclick="dropLocalStorage()">Logout</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% block content %}{% endblock content %}
</div>
<script src="{% static 'compiler/constants.js' %}"></script>
<script src="{% static 'compiler/themes.js' %}"></script>
<script src="{% static 'compiler/main.js' %}"></script>
</body>

</html>

wa/compiler/templates/compiler/directories-tree.html
<li>
    {% if dir.is_file %}
        <i class="fa fa-file-o" aria-hidden="true"></i>
    {% else %}
        <i class="fa fa-folder-o" aria-hidden="true"></i>
    {% endif %}
    {% if dir.is_file %}
        <a class="file" href="#" onclick="displayFileAndSaveId({{ dir.info.id }})">
            {{ dir.info.name }}
        </a>
    {% else %}
        <a class="file" href="#" onclick="saveFileIdToForm('{{ dir.info.id }}', '{{ dir.info.name }}')"
           data-bs-toggle="modal" data-bs-target="#exampleModal">
            {{ dir.info.name }}
        </a>
    {% endif %}
    {% if dir.has_children %}
        <ul>
            {% for dirchild in dir.get_children %}
                {% with dir=dirchild template_name="compiler/directories-tree.html" %}
                    {% include template_name %}
                {% endwith %}
            {% endfor %}
        </ul>
    {% endif %}
</li>

wa/compiler/templates/compiler/directories.html
<ul>
    {% for dir in directories %}
        {% include "compiler/directories-tree.html" %}
    {% endfor %}
</ul>

wa/compiler/templates/compiler/index.html
{% extends "compiler/base.html" %}
{% load static %}

{% block content %}
    <div class="grid-item choose-file">
        <button class="btn btn-outline-light w-100" onclick="saveFileIdToForm('-1', 'Root')"
                data-bs-toggle="modal" data-bs-target="#exampleModal" style="height: 40px">
            <i class="fa fa-folder-open-o" aria-hidden="true" style="margin-right: 5px"></i>Root directory
        </button>
        <div class="directory-structure" id="tree">
            {% include "compiler/directories.html" %}
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Upload file to chosen directory:</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button class="nav-link active" id="create-tab" data-bs-toggle="tab"
                                        data-bs-target="#create" type="button" role="tab" aria-controls="create"
                                        aria-selected="true">Create directory
                                </button>
                            </li>
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="upload-tab" data-bs-toggle="tab" data-bs-target="#upload"
                                        type="button" role="tab" aria-controls="upload" aria-selected="false">
                                    Upload file
                                </button>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade p-2 show active" id="create" role="tabpanel"
                                 aria-labelledby="create-tab">
                                <form method="post" id="create-directory-form">
                                    {% csrf_token %}
                                    {{ directoryForm.name }}
                                    {{ directoryForm.description }}
                                    {{ directoryForm.parent }}
                                </form>
                                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"
                                        onclick="createDirectory()" id="create-btn">
                                    Create
                                </button>
                            </div>
                            <div class="tab-pane fade p-2" id="upload" role="tabpanel" aria-labelledby="upload-tab">
                                <form method="post" id="upload-form">
                                    {% csrf_token %}
                                    {{ fileForm.file }}
                                    {{ fileForm.description }}
                                    {{ fileForm.parent }}
                                </form>
                                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"
                                        onclick="uploadFile()" id="upload-btn">
                                    Upload
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal"
                                onclick="deleteFile()" id="delete-btn">
                            Delete
                        </button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-item program-content">
        <div class="editor-panel">
            <form method="post" id="sections-form" class="panel-component">
                {% csrf_token %}
                {{ sectionsForm.start }}
                {{ sectionsForm.end }}
                {{ sectionsForm.sectionType }}
            </form>
            <button class="btn btn-primary panel-component" onclick="changeSections()">Change selected</button>
            <button class="btn btn-success panel-component" onclick="compileFile()">Compile</button>
            <button class="btn btn-danger panel-component" onclick="deleteChosenFile()">Delete</button>
        </div>
        <textarea id="editor"></textarea>
    </div>
    <div class="grid-item code-fragment">
        <div class="mb-0 h-100 w-100 overflow-auto" id="output"></div>
    </div>
    <div class="grid-item compile-options">
        <div class="d-flex align-items-start">
            <div class="nav flex-column nav-pills me-3 ml-0" id="v-pills-tab" role="tablist"
                 aria-orientation="vertical">
                <button class="nav-link active" id="v-pills-processor-tab" data-bs-toggle="pill"
                        data-bs-target="#v-pills-processor" type="button" role="tab" aria-controls="v-pills-processor"
                        aria-selected="true">Processor
                </button>
                <button class="nav-link" id="v-pills-optimization-tab" data-bs-toggle="pill"
                        data-bs-target="#v-pills-optimization" type="button" role="tab"
                        aria-controls="v-pills-optimization"
                        aria-selected="false">Optimization
                </button>
                <button class="nav-link" id="v-pills-standard-tab" data-bs-toggle="pill"
                        data-bs-target="#v-pills-standard" type="button" role="tab" aria-controls="v-pills-standard"
                        aria-selected="false">Standard
                </button>
                <button class="nav-link" id="v-pills-options-tab" data-bs-toggle="pill"
                        data-bs-target="#v-pills-options" type="button" role="tab" aria-controls="v-pills-options"
                        aria-selected="false">Options
                </button>
            </div>
            <form method="post" id="compile-form">
                {% csrf_token %}
                <div class="tab-content compile-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-processor" role="tabpanel"
                         aria-labelledby="v-pills-processor-tab">
                        Choose processor for compilation.
                        {{ form.processor }}
                    </div>
                    <div class="tab-pane fade" id="v-pills-optimization" role="tabpanel"
                         aria-labelledby="v-pills-optimization-tab">
                        Choose optimizations for compilation (multiple choice).
                        {{ form.optimization }}
                    </div>
                    <div class="tab-pane fade" id="v-pills-standard" role="tabpanel"
                         aria-labelledby="v-pills-standard-tab">
                        Choose standard for compilation.
                        {{ form.standard }}
                    </div>
                    <div class="tab-pane fade" id="v-pills-options" role="tabpanel"
                         aria-labelledby="v-pills-options-tab">
                        Choose options for your processor, options for other processors will be omitted.
                        <div class="form-group">
                            {{ form.options_AVR }}
                            {{ form.options_MCS51 }}
                            {{ form.options_Z80 }}
                            {{ form.options_STM8 }}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}